name 'nginx_service'
maintainer 'Salar Hafezi'
maintainer_email 'salar.hfz@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures nginx_service'
version '0.1.0'
chef_version '>= 15.0'
