name 'myhaproxy'
maintainer 'Salar Hafezi'
maintainer_email 'salar.hfz@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures haproxy'
version '0.1.0'
chef_version '>= 15.0'
depends 'haproxy', '~> 9.1.0'
