name 'apache_service'
maintainer 'Salar Hafezi'
maintainer_email 'salar.hfz@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures apache_service'
version '0.4.0'
chef_version '>= 15.0'
